version: "3.8"

services:
  icarus-fog-rabbitmqbroker:
    image: cricarusprod001.azurecr.io/icarus-fog-rabbitmqbroker
    container_name: icarus-fog-rabbitmqbroker
    ports:
      - 5671:5671
      - 5672:5672
    volumes:
      - ${PWD}/dev/certs/root_ca.crt:/etc/rabbitmq/ssh/ss_certs/root_ca.crt:ro
      - ${PWD}/dev/certs/client-1.crt:/etc/rabbitmq/ssh/ss_certs/client.crt:ro
      - ${PWD}/dev/certs/client-1.key:/etc/rabbitmq/ssh/ss_certs/client.key:ro
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_BROKER_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_BROKER_PASSWORD:-guest}
      # - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/config/rabbitmq.conf
    restart: always

  icarus-fog-webserver-rabbitmq:
    image: cricarusprod001.azurecr.io/icarus-fog-webserver
    container_name: icarus-fog-webserver-rabbitmq
    entrypoint: [ "./scripts/start.rabbitmq.sh" ]
    environment:
      - DB_USER_USERNAME=postgres
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-fog-storage
    depends_on:
      - icarus-fog-rabbitmqbroker
    restart: always

  icarus-fog-webserver:
    image: cricarusprod001.azurecr.io/icarus-fog-webserver
    container_name: icarus-fog-webserver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    ports:
      - 8000:8000
    environment:
      - DB_USER_USERNAME=postgres
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-fog-storage
    depends_on:
      - icarus-fog-storage
    restart: always

  icarus-fog-filesaver:
    image: cricarusprod001.azurecr.io/icarus-fog-filesaver
    # container_name: icarus-filesaver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    expose:
      - "8000"
    environment:
      - HOST_MOUNT_PATH=/home/docker_user/data
    volumes:
      - ${HOME}/data/tmp/filesaver:/home/docker_user/data
    depends_on:
      - icarus-fog-rabbitmqbroker
    restart: always

  icarus-fog-storage:
    image: cricarusprod001.azurecr.io/icarus-fog-storage
    container_name: icarus-fog-storage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  icarus-fog-proxy:
    image: cricarusprod001.azurecr.io/icarus-fog-proxy
    container_name: icarus-fog-proxy
    ports:
      - 8443:443
    volumes:
      - ./dev/certs/client-1.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./dev/certs/client-1.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      - icarus-fog-webserver
    restart: always

  # Debug containers
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
