version: "3.8"

services:
  icarus-fog-rabbitmqbroker:
    build:
      context: icarus-fog-rabbitmqbroker
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-fog-rabbitmqbroker

  icarus-fog-webserver:
    build:
      context: icarus-fog-webserver
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-fog-webserver

  icarus-fog-storage:
    build:
      context: icarus-fog-storage
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-fog-storage

  icarus-fog-proxy:
    build:
      context: icarus-fog-proxy
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-fog-proxy
