version: "3.8"

services:
  icarus-rabbitmqbroker:
    image: prominendt/icarus-dev:amd64-demo-rabbitmqbroker
    container_name: icarus-rabbitmqbroker
    ports:
      - 5671:5671
    volumes:
      - ./dev/certs/root_ca.crt:/etc/rabbitmq/ssh/ss_certs/root_ca.crt:ro
      - ./dev/certs/client-1.crt:/etc/rabbitmq/ssh/ss_certs/client.crt:ro
      - ./dev/certs/client-1.key:/etc/rabbitmq/ssh/ss_certs/client.key:ro
    restart: unless-stopped

  icarus-webserver-rabbitmq:
    image: prominendt/icarus-dev:amd64-demo-webserver
    container_name: icarus-webserver-rabbitmq
    entrypoint: [ "./scripts/start.rabbitmq.sh" ]
    environment:
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-storage
    depends_on:
      - icarus-storage
    restart: unless-stopped

  icarus-webserver:
    image: prominendt/icarus-dev:amd64-demo-webserver
    container_name: icarus-webserver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    ports:
      - 8000:8000
    environment:
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-storage
    depends_on:
      - icarus-storage
    restart: unless-stopped

  icarus-filesaver:
    image: prominendt/icarus-dev:amd64-demo-filesaver
    # container_name: icarus-filesaver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    expose:
      - "8000"
    environment:
      - HOST_MOUNT_PATH=/home/docker_user/data
    volumes:
      - ${HOME}/data/tmp/filesaver:/home/docker_user/data
    depends_on:
      - icarus-rabbitmqbroker
    restart: unless-stopped

  icarus-storage:
    image: prominendt/icarus-dev:amd64-demo-storage
    container_name: icarus-storage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  icarus-proxy:
    image: prominendt/icarus-dev:amd64-demo-proxy
    container_name: icarus-proxy
    ports:
      - 8443:443
    volumes:
      - ./dev/certs/client-1.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./dev/certs/client-1.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      - icarus-webserver
    restart: unless-stopped

  # Debug containers
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
