version: "3.8"

services:
  icarus-rabbitmqbroker:
    image: prominendt/icarus-dev:amd64-demo-rabbitmqbroker
    container_name: icarus-rabbitmqbroker
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    restart: always

  icarus-webserver-rabbitmq:
    image: prominendt/icarus-dev:amd64-demo-webserver
    container_name: icarus-webserver-rabbitmq
    entrypoint: [ "./scripts/start.rabbitmq.sh" ]
    environment:
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-storage
    depends_on:
      - icarus-storage

  icarus-webserver:
    image: prominendt/icarus-dev:amd64-demo-webserver
    container_name: icarus-webserver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    ports:
      - 8000:8000
    environment:
      - DB_USER_PASSWORD=postgres
      - DB_IP_ADDRESS=icarus-storage
    depends_on:
      - icarus-storage

  icarus-filesaver:
    image: prominendt/icarus-dev:amd64-demo-filesaver
    container_name: icarus-filesaver
    entrypoint: [ "./scripts/start.fastapi.sh" ]
    ports:
      - 7000:8000
    environment:
      - HOST_MOUNT_PATH=/home/docker_user/data
    depends_on:
      - icarus-rabbitmqbroker

  icarus-storage:
    image: prominendt/icarus-dev:amd64-demo-storage
    container_name: icarus-storage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  icarus-proxy:
    image: prominendt/icarus-dev:amd64-demo-proxy
    container_name: icarus-proxy
    ports:
      - 5000:80
    depends_on:
      - icarus-webserver
    restart: unless-stopped

  # Debug containers
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
